Repository similarweb/finala, pull requests merged in 2020-07, with the labels that each got.

#73 Add the option to filter resources by Tags in the API
  CHANGELOG.md
  api/httpparameters/get.go
  api/httpparameters/get_test.go
  api/route.go
  api/server.go
  api/server_test.go
  api/storage/elasticsearch/elasticsearch.go
  api/storage/elasticsearch/structs.go
  api/storage/structs.go
  api/testutils/storage.go
  go.mod
  go.sum
  interpolation/interpolation.go
  interpolation/interpolation_test.go
  notifiers/providers/slack/slack.go
  notifiers/providers/slack/slack_private_test.go
Labels: enhancement, lgtm

#77 Fix tags query size for Elasticsearch
  api/storage/elasticsearch/elasticsearch.go
Labels: bug, lgtm

#78 Add golangci + gofmt and fix the errors
  .github/workflows/fmt.yaml
  .github/workflows/lint.yaml
  CHANGELOG.md
  Makefile
  README.md
  api/server.go
  api/storage/elasticsearch/elasticsearch.go
  api/testutils/storage.go
  cmd/root.go
  collector/aws/cloudwatch.go
  collector/aws/cloudwatch_test.go
  collector/aws/docdb.go
  collector/aws/docdb_test.go
  collector/aws/ec2.go
  collector/aws/ec2_test.go
  collector/aws/ec2volumes.go
  collector/aws/ec2volumes_test.go
  collector/aws/elasticache.go
  collector/aws/elasticache_test.go
  collector/aws/elb.go
  collector/aws/elb_test.go
  collector/aws/elbv2.go
  collector/aws/elbv2_test.go
  collector/aws/iam.go
  collector/aws/lambda.go
  collector/aws/neptune.go
  collector/aws/neptune_test.go
  collector/aws/pricing.go
  collector/aws/pricing_test.go
  collector/aws/rds.go
  collector/aws/rds_test.go
  collector/aws/redshift.go
  collector/aws/run.go
  collector/collector_test.go
  expression/expression.go
  notifiers/config/config_test.go
  notifiers/notifier_test.go
  notifiers/providers/slack/slack_private_test.go
  notifiers/testutil/mocks.go
  request/http_test.go
  serverutil/server_test.go
  webserver/server.go
Labels: lgtm

#79 Add Code Cov to repo
  .github/workflows/go.yml
  README.md
Labels: enhancement, lgtm

#76 Fix the pricing for ELB
  CHANGELOG.md
  collector/aws/elb.go
  collector/aws/elb_test.go
  collector/aws/elbv2.go
  collector/aws/elbv2_test.go
  collector/aws/pricing.go
  collector/aws/pricing_test.go
Labels: bug, lgtm

#81 Feature/improve ci cd
  .github/workflows/go.yml
  .github/workflows/release.yaml
  .github/workflows/security.yaml
  .goreleaser.yml
  Dockerfile
  Dockerfile.dev
  Makefile
  build-support/build.sh
  cmd/root.go
Labels: enhancement, lgtm

#82 Change GoRelease to have the correct semver tags
  .github/workflows/release.yaml
Labels: bug

#83 Fix the Dockerfile release download
  Dockerfile
Labels: bug, lgtm

#86 Add codecov config
  codecov.yml
Labels: enhancement, lgtm

#84 Fix version preview
  cmd/root.go
Labels: bug, lgtm

#87 Don't change the Tag Key , use the original from AWS
  api/storage/elasticsearch/elasticsearch.go
Labels: bug, lgtm

#90 Remove Notifier from Docker compose first run.
  api/storage/elasticsearch/elasticsearch.go
  docker-compose.yaml
Labels: bug, lgtm

#97 add elastic ip resource
  collector/aws/ec2.go
  collector/aws/elasticips.go
  collector/aws/elasticips_test.go
  collector/aws/run.go
  collector/config/config.go
  configuration/collector.yaml
Labels: enhancement, lgtm

#99 Remove totalSpend field
  collector/aws/docdb.go
  collector/aws/dynamodb.go
  collector/aws/ec2.go
  collector/aws/elasticache.go
  collector/aws/elb.go
  collector/aws/elbv2.go
  collector/aws/kinesis.go
  collector/aws/lambda.go
  collector/aws/neptune.go
  collector/aws/rds.go
  collector/aws/redshift.go
  collector/structs.go
Labels: enhancement, lgtm

#100 Feature/metrics enable flag
  cmd/collector.go
  collector/aws/run.go
  collector/config/config.go
  collector/metrics.go
  collector/metrics_test.go
  configuration/collector.yaml
Labels: enhancement, lgtm

#98 Feature/add elasticsearch resource detection
  collector/aws/elasticsearch.go
  collector/aws/elasticsearch_test.go
  collector/aws/run.go
  collector/aws/sts.go
  configuration/collector.yaml
  go.sum
  interpolation/interpolation.go
  interpolation/interpolation_test.go
Labels: enhancement, lgtm

#102 Add ec2 volumes detection to collector configuration
  collector/aws/run.go
  configuration/collector.yaml
Labels: enhancement, lgtm

#103 routing fixes for README.
  docs/components.md
  docs/developers/add-new-notifier.md
  docs/install/local-install.md
Labels: documentation, lgtm

#85 Feature/revamp-ui
  .gitignore
  ui/.eslintrc
  ui/config/webpack.config.base.js
  ui/package-lock.json
  ui/package.json
  ui/server/middleware.development.js
  ui/src/App.js
  ui/src/components/Dashboard/FilterBar.js
  ui/src/components/Dashboard/Index.js
  ui/src/components/Dashboard/ResourceScanning.js
  ui/src/components/Dashboard/ResourceTable.js
  ui/src/components/Dashboard/ResourcesChart.js
  ui/src/components/Dashboard/ResourcesList.js
  ui/src/components/Dashboard/StatisticsBar.js
  ui/src/components/Dashboard/colors.json
  ui/src/components/Dialog/Tags.js
  ui/src/components/Executions/Index.js
  ui/src/components/Header.js
  ui/src/components/LeftBar.js
  ui/src/components/Logo/index.js
  ui/src/components/NoData.js
  ui/src/components/NotFound.js
  ui/src/components/PageLoader.js
  ui/src/components/Resource/Index.js
  ui/src/components/Resource/table.js
  ui/src/configureStore.js
  ui/src/directives/Index.js
  ui/src/directives/Money.js
  ui/src/directives/Title.js
  ui/src/index.html
  ui/src/index.js
  ui/src/reducers/executions.reducer.js
  ui/src/reducers/filters.reducer.js
  ui/src/reducers/index.js
  ui/src/reducers/resources.reducer.js
  ui/src/routes/index.js
  ui/src/services/request.service.js
  ui/src/services/resources.service.js
  ui/src/services/settings.service.js
  ui/src/services/tags.service.js
  ui/src/styles/icons/icon.png
  ui/src/styles/icons/logo.png
  ui/src/styles/index.scss
  ui/src/utils/Text.js
Labels: enhancement, lgtm

#109 Improve pricing tests
  collector/aws/pricing/pricing.go
  collector/aws/pricing/pricing_test.go
  collector/aws/resources/docdb.go
  collector/aws/resources/dynamodb.go
  collector/aws/resources/ec2.go
  collector/aws/resources/ec2volumes.go
  collector/aws/resources/elasticache.go
  collector/aws/resources/elasticips.go
  collector/aws/resources/elasticsearch.go
  collector/aws/resources/elb.go
  collector/aws/resources/elbv2.go
  collector/aws/resources/kinesis.go
  collector/aws/resources/neptune.go
  collector/aws/resources/rds.go
  collector/aws/resources/redshift.go
Labels: enhancement, lgtm

#106 trends feature
  api/route.go
  api/server.go
  api/server_test.go
  api/storage/elasticsearch/elasticsearch.go
  api/storage/structs.go
  api/testutils/storage.go
  interpolation/interpolation.go
  interpolation/interpolation_test.go
Labels: enhancement, lgtm

#110 Feature/tests improve docdb
  collector/aws/resources/docdb_test.go
  collector/aws/testutils/metric.go
  collector/aws/testutils/pricing.go
Labels: enhancement, lgtm

#113 Fix total records response
  api/storage/elasticsearch/elasticsearch.go
Labels: bug, lgtm

#116 Disable patch
  codecov.yml
Labels: enhancement

#111 Feature/add apigateway
  README.md
  collector/aws/resources/apigateway.go
  collector/aws/resources/apigateway_test.go
  configuration/collector.yaml
Labels: enhancement, lgtm

#115 create index per day
  api/config/config.go
  api/storage/elasticsearch/date.go
  api/storage/elasticsearch/date_test.go
  api/storage/elasticsearch/elasticsearch.go
  configuration/api.yaml
Labels: enhancement, lgtm

#117 add prerelease
  .goreleaser.yml
Labels: enhancement, lgtm

#114 Add support for Version notification on a new version,
  .goreleaser.yml
  api/route.go
  api/server.go
  api/server_test.go
  api/testutils/version.go
  cmd/api.go
  cmd/root.go
  go.mod
  go.sum
  structs/storage.go
  version/version.go
  version/version_test.go
Labels: enhancement, lgtm

#123 Add more kinds of DatabaseEngines to RDS
  collector/aws/resources/rds.go
  collector/aws/resources/rds_test.go
Labels: bug, component:collector, lgtm

#105 Format changelog with a spcific standard.
  CHANGELOG.md
Labels: documentation, lgtm
