Repository similarweb/finala, pull requests merged in 2020-09, with the labels that each got.

#145 Make sure all Kinesis Streams are retrieved
  collector/aws/resources/kinesis.go
  collector/aws/resources/kinesis_test.go
Labels: area/collector, kind/bug, lgtm

#146 support direct table filter link
  ui/src/Hooks/TableHooks.js
  ui/src/components/Dashboard/FilterBar.js
  ui/src/components/Dashboard/Index.js
  ui/src/components/Dashboard/ResourceTable.js
  ui/src/utils/History.js
Labels: area/ui, kind/new-feature, lgtm

#138 Feature/es testing
  api/storage/elasticsearch/client.go
  api/storage/elasticsearch/elasticsearch.go
  api/storage/elasticsearch/elasticsearch_test.go
  api/storage/elasticsearch/testutils/client.go
  api/storage/elasticsearch/testutils/responses/executions/aggregations/default.json
  api/storage/elasticsearch/testutils/responses/executions/aggregations/invalid-aggregations-key.json
  api/storage/elasticsearch/testutils/responses/resources/default.json
  api/storage/elasticsearch/testutils/responses/trends/buckets.json
  api/testutils/server.go
  cmd/api.go
Labels: area/api, kind/tests, lgtm

#143 Bug/rds calculation is missing additional costs
  collector/aws/resources/rds.go
  collector/aws/resources/rds_test.go
Labels: area/collector, kind/bug, lgtm

#151 fix exact match query
  api/storage/elasticsearch/elasticsearch.go
  api/storage/elasticsearch/elasticsearch_test.go
Labels: area/api, kind/bug, lgtm

#153 fix docker compose
  ui/src/components/Dashboard/FilterBar.js
  ui/src/components/Dashboard/ResourceScanning.js
  ui/src/components/Dashboard/ResourcesChart.js
  ui/src/components/Dashboard/ResourcesList.js
  ui/src/components/Dashboard/StatisticsBar.js
  ui/src/components/DataFactory.js
  ui/src/components/Executions/Index.js
  ui/src/directives/Index.js
  ui/src/utils/Money.js
  ui/src/utils/Title.js
Labels: area/ui, kind/bug, lgtm

#152 Update readme with an important note.
  README.md
Labels: kind/documentation, lgtm

#154 Update changelog with the latest release
  CHANGELOG.md
Labels: kind/documentation, lgtm

#155 Add quick start to main readme.
  README.md
  docs/images/dashboard.png
  docs/images/main-dashboard.png
  docs/images/resource.jpg
Labels: kind/documentation, lgtm
