Repository similarweb/finala, pull requests merged in 2020-06, with the labels that each got.

#52 Add the support to detect under-utilized Neptune
  .vscode/launch.json
  .vscode/settings.json
  CHANGELOG.md
  README.md
  api/server.go
  cmd/root.go
  collector/aws/neptune.go
  collector/aws/neptune_test.go
  collector/aws/run.go
  configuration/collector.yaml
  configuration/ui.yaml
  go.mod
  go.sum
  webserver/server.go
Labels: enhancement

#56 Add the option to notify by tags to a notification group
  README.md
  api/httpparameters/get.go
  api/httpparameters/get_test.go
  api/route.go
  api/server.go
  api/server_test.go
  api/storage/elasticsearch/elasticsearch.go
  api/storage/structs.go
  api/testutils/storage.go
  cmd/collector.go
  cmd/notifier.go
  cmd/root.go
  configuration/notifier.yaml
  docker-compose.yaml
  docs/notifiers/add-new-notifier.md
  docs/slack.png
  go.mod
  go.sum
  notifiers/common/common.go
  notifiers/common/structs.go
  notifiers/config/config.go
  notifiers/config/config_test.go
  notifiers/config/testutil/mock/config.yaml
  notifiers/load/load.go
  notifiers/load/load_test.go
  notifiers/notifier.go
  notifiers/notifier_test.go
  notifiers/providers/slack/slack.go
  notifiers/providers/slack/slack_private_test.go
  notifiers/providers/slack/slack_test.go
  notifiers/providers/slack/structs.go
  notifiers/register.go
  notifiers/register_test.go
  notifiers/testutil/mocks.go
  ui/src/services/resources.service.js
Labels: bug, enhancement, lgtm

#59 Feature/add kinesis resource detection
  CHANGELOG.md
  README.md
  collector/aws/docdb.go
  collector/aws/dynamodb.go
  collector/aws/ec2.go
  collector/aws/ec2volumes.go
  collector/aws/elasticache.go
  collector/aws/elb.go
  collector/aws/elbv2.go
  collector/aws/kinesis.go
  collector/aws/kinesis_test.go
  collector/aws/neptune.go
  collector/aws/pricing.go
  collector/aws/pricing_test.go
  collector/aws/rds.go
  collector/aws/run.go
  collector/structs.go
  configuration/collector.yaml
  go.sum
Labels: bug, enhancement

#60 Fixed a bug for the collector resource status
  CHANGELOG.md
  cmd/root.go
  collector/structs.go
Labels: bug, lgtm

#63 Add the total potential costs for a notification group
  api/storage/structs.go
  notifiers/providers/slack/slack.go
  notifiers/providers/slack/slack_private_test.go
Labels: enhancement, lgtm

#64 Support multiple price regions
  collector/aws/dynamodb.go
  collector/aws/dynamodb_test.go
Labels: lgtm

#58 Update spectralops ci to get the latest code
  .github/workflows/go.yml
Labels: lgtm

#65 Bump version and update changelog
  CHANGELOG.md
  cmd/root.go
Labels: documentation

#71 Ignore Neptune engine in RDS collection
  CHANGELOG.md
  collector/aws/rds.go
Labels: bug, lgtm

#74 Add Redshift resource detection
  README.md
  collector/aws/redshift.go
  collector/aws/redshift_test.go
  collector/aws/run.go
  configuration/collector.yaml
Labels: enhancement, lgtm
