Repository similarweb/finala, pull requests merged in 2020-03, with the labels that each got.

#31 Notify when new Finala version release
  CHANGELOG.md
  cmd/root.go
  go.mod
  go.sum
Labels: enhancement, lgtm

#32 change CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: documentation

#33 Improve CI process
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/support.md
  .github/pull_request_template.md
  .github/workflows/go.yml
  .travis.yml
Labels: enhancement

#30 Feature/add alb support
  .vscode/launch.json
  README.md
  config.yaml
  provider/aws/elbv2.go
  provider/aws/elbv2_test.go
  provider/aws/run.go
Labels: enhancement

#37 Fix typo
  cmd/root.go
Labels: bug

#40 Feature/dockerize project
  .dockerignore
  Dockerfile
  README.md
  cmd/root.go
  config.yaml
  webserver/server.go
Labels: enhancement, lgtm

#36 Detect IAM user last activity
  README.md
  cmd/aws.go
  config.yaml
  config/config.go
  go.mod
  go.sum
  provider/aws/iam.go
  provider/aws/iam_test.go
  provider/aws/run.go
  storage/mysql.go
Labels: enhancement, lgtm

#38 Support pagination
  provider/aws/docdb.go
  provider/aws/docdb_test.go
  provider/aws/ec2.go
  provider/aws/ec2_test.go
  provider/aws/ec2volumes.go
  provider/aws/ec2volumes_test.go
  provider/aws/elasticache.go
  provider/aws/elasticache_test.go
  provider/aws/elb.go
  provider/aws/elb_test.go
  provider/aws/elbv2.go
  provider/aws/elbv2_test.go
  provider/aws/lambda.go
  provider/aws/lambda_test.go
  provider/aws/rds.go
  provider/aws/rds_test.go
Labels: bug, lgtm
